import Head from 'next/head'
import Image from 'next/image'
import classes from '../styles/Home.module.scss';

export default function Home() {
  return (
    <div className={classes.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={classes.main}>
        <h1 className={classes.title}>
          Welcome to ACCSESSLONG STORE
        </h1>
      </main>

      <footer className={classes.footer}>
        
      </footer>
    </div>
  )
}
